apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ratings-service
spec:
  template:
    metadata:
      name: ratings-service-v1
    spec:
      imagePullSecrets:
      - name: {{ .Values.secretName }}
      containers:
      - name: ratings
        image: iad.ocir.io/idmaqhrbiuyo/ratings:v0.1
        ports:
        - containerPort: 3002
        readinessProbe:
          httpGet:
            path: /
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 2   
        resources:
          limits:
            cpu:  {{ .Values.limitCPU }}
            memory:  {{ .Values.limitMemory }}
          requests:
            cpu:  {{ .Values.requestCPU }}
            memory:  {{ .Values.requestMemory }}